

title: Macro Polo China Tour
email: lolawork731@icloud.com
       k20025130@kcl.ac.uk
       holashea@163.com
description: >- # this means to ignore newlines until "baseurl:"
  This archive presents users with the wonderful stories of Marco Polo, an outstanding historical figure, traveling in China, and records what he saw and heard in various regions of China. The structure of this website includes introduction to the original works, introduction to Marco Polo, travel stories, disputes and references. This archive is mainly for historians, travel enthusiasts or academic researchers to provide them with valuable digital assets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcopolochinatour.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings

plugins:
  - jekyll-feed
collections:
  - exhibit
  - collection
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
